language: scala
scala:
  - 2.11.2
jdk:
  - oraclejdk7
  - openjdk7
addons:
  postgresql: "9.3"
services:
  - postgresql
before_script:
  - ./script/prepare_build.sh

notifications:
  email:
    - nick@comdevelopment.com
